apiVersion: v1
kind: Service
metadata:
  name: ${USER_ID}-java-svc
  labels:
    app: ${USER_ID}--name
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${USER_ID}-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${USER_ID}-java-deploy
  labels:
    app: ${USER_ID}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${USER_ID}-app
  template:
    metadata:
      labels:
        app: ${USER_ID}-app
    spec:
      containers:
        - name: ${USER_ID}-container
          image: ${K8S_BASE_IMAGE}
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          - containerPort: 8009
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: / 
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
      nodeSelector:
        kubernetes.io/role: training  
