apiVersion: v1
kind: Service
metadata:
  name: ${USER_ID}-node-svc
  labels:
    app: ${USER_ID}-node-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: ${USER_ID}-node-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${USER_ID}-node-deploy
  labels:
    app: ${USER_ID}-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${USER_ID}-node-app
  template:
    metadata:
      labels:
        app: ${USER_ID}-node-app
    spec:
      containers:
        - name: ${USER_ID}-container
          image: ${K8S_BASE_IMAGE}
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
            #          livenessProbe:
            #            httpGet:
            #              path: /
            #             port: 3000
            #    initialDelaySeconds: 60
            #            periodSeconds: 3
            #      failureThreshold: 10
            #     readinessProbe:
            #     httpGet:
            #        path: / 
            #        port: 3000
            #    initialDelaySeconds: 60
            #      periodSeconds: 5
      nodeSelector:
        kubernetes.io/role: training
